build:
    tags:
        - Ubuntu1804-64bit
    script:
        - sudo apt-get -y update
        - sudo apt-get -y install python3-pip libcairo2-dev
        - cd  ./package/cmtrace/cmtrace/tests
        - python3 -m pip install pytest yaml
        - python3 -m pytest . -v

    artifacts:
      expire_in: 14d
      when: always
      paths:
      - /builds/computational-modeling/cmtrace/package/cmtrace/cmtrace/test/output/
