build:
    tags:
        - Ubuntu1804-64bit
    script:
        - sudo apt-get -y update
        - sudo apt-get -y install python3-pip libcairo2-dev
        - cd  ./package/cmtrace/cmtrace/tests
        - python3 -m pip install pytest pyyaml svgwrite pycairo
        - python3 -m pytest . -v

